[2025-08-13T13:08:12.604+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_data manual__2025-08-13T13:08:07.824089+00:00 [queued]>
[2025-08-13T13:08:12.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_etl_pipeline.load_data manual__2025-08-13T13:08:07.824089+00:00 [queued]>
[2025-08-13T13:08:12.621+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-08-13T13:08:12.650+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data> on 2025-08-13 13:08:07.824089+00:00
[2025-08-13T13:08:12.661+0000] {standard_task_runner.py:57} INFO - Started process 203 to run task
[2025-08-13T13:08:12.667+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_etl_pipeline', 'load_data', 'manual__2025-08-13T13:08:07.824089+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl.py', '--cfg-path', '/tmp/tmpd74ud4ks']
[2025-08-13T13:08:12.672+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask load_data
[2025-08-13T13:08:12.719+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:193 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-08-13T13:08:12.778+0000] {task_command.py:416} INFO - Running <TaskInstance: weather_etl_pipeline.load_data manual__2025-08-13T13:08:07.824089+00:00 [running]> on host 5981a842327b
[2025-08-13T13:08:12.997+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-13T13:08:07.824089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-13T13:08:07.824089+00:00'
[2025-08-13T13:08:13.041+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-08-13T13:08:13.049+0000] {base.py:73} INFO - Using connection ID 'postgres_weather' for task execution.
[2025-08-13T13:08:13.207+0000] {logging_mixin.py:151} INFO - Loaded 150 rows into PostgreSQL.
[2025-08-13T13:08:13.212+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-08-13T13:08:13.247+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=weather_etl_pipeline, task_id=load_data, execution_date=20250813T130807, start_date=20250813T130812, end_date=20250813T130813
[2025-08-13T13:08:13.316+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-13T13:08:13.400+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
